pull_request_rules:
  - name: Automatic merge
    conditions:
        - title=Update flake.lock
        - or:
            - author=github-actions[bot]
            - author=TibiIius
    actions:
      merge:
        method: merge
      delete_head_branch: