# This builds the configurations defined in the Nix Flake file

name: Build Nix configurations

on:
  workflow_dispatch:
  pull_request:
    paths: ["hosts/*/**", "home/*/**", "flake.{nix,lock}"]
  push:
    branches:
      - master
    paths: ["hosts/*/**", "home/*/**", "flake.{nix,lock}"]

jobs:
  build:
    name: Build Nix configurations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Login and push artifacts to cachix
        uses: cachix/cachix-action@v12
        # This way, the build doesn't get uploaded on a PR, only on a push to master
        if: github.event_name != 'pull_request'
        with:
          name: tibilius-cache
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build home configuration
        run: nix build .#homeConfigurations.tim.activationPackage
