# This builds the configurations defined in the Nix Flake file

name: Build Nix configurations

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Nix configurations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v12
        with:
          name: tibilius-cache
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build home configuration
        run: nix build .#homeConfigurations.tim.activationPackage
