# This is a basic workflow to help you get started with Actions

name: Update flake.lock

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1,3,5"
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
      - run: nix flake update --commit-lock-file
      - uses: peter-evans/create-pull-request@v3
        with:
          branch: lock-update
          delete-branch: true
          title: "[flake.lock] Update"
